# Generated by Django 4.2.16 on 2024-09-30 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.CharField(choices=[('Добавлено', 'Добавлено'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено')], default='Добавлено', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=32, max_length=10),
            preserve_default=False,
        ),
    ]
